### ISSUE TITLE
Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by nilov** [NetanelBasal/ngx-text-equality-validator#2]
Hi! I have this error when I destroy component where is this directive.

**Comment by dfederm** [comment]
I'm also seeing this.

```
ERROR Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at new SafeSubscriber (Subscriber.js?9a65:156)
    at new Subscriber (Subscriber.js?9a65:59)
    at Object.toSubscriber (toSubscriber.js?947b:17)
    at EventEmitter.Observable.subscribe (Observable.js?ac24:154)
    at EventEmitter.subscribe (core.es5.js?de3d:3657)
    at TextEqualityValidatorDirective.validate (ngx-text-equality-validator.bundle.js?d5d0:125)
    at eval (forms.es5.js?3553:757)
    at eval (forms.es5.js?3553:506)
    at Array.map (<anonymous>)
    at _executeValidators (forms.es5.js?3553:506)
    at eval (forms.es5.js?3553:462)
    at eval (forms.es5.js?3553:506)
    at Array.map (<anonymous>)
    at _executeValidators (forms.es5.js?3553:506)
    at FormControl.eval [as validator] (forms.es5.js?3553:462)
    at FormControl.AbstractControl._runValidator (forms.es5.js?3553:2720)
    at FormControl.AbstractControl.updateValueAndValidity (forms.es5.js?3553:2688)
    at TextEqualityValidatorDirective.eval [as _onChange] (forms.es5.js?3553:1856)
    at eval (ngx-text-equality-validator.bundle.js?d5d0:127)
    at SafeSubscriber.schedulerFn [as _next] (core.es5.js?de3d:3647)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js?9a65:238)
    at SafeSubscriber.next (Subscriber.js?9a65:185)
    at Subscriber._next (Subscriber.js?9a65:125)
    at Subscriber.next (Subscriber.js?9a65:89)
    at EventEmitter.Subject.next (Subject.js?104a:55)
    at EventEmitter.emit (core.es5.js?de3d:3621)
    at FormGroup.AbstractControl.updateValueAndValidity (forms.es5.js?3553:2695)
    at FormControl.AbstractControl.updateValueAndValidity (forms.es5.js?3553:2699)
    at TextEqualityValidatorDirective.eval [as _onChange] (forms.es5.js?3553:1856)
    at eval (ngx-text-equality-validator.bundle.js?d5d0:127)
    at SafeSubscriber.schedulerFn [as _next] (core.es5.js?de3d:3647)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js?9a65:238)
    at SafeSubscriber.next (Subscriber.js?9a65:185)
    at Subscriber._next (Subscriber.js?9a65:125)
    at Subscriber.next (Subscriber.js?9a65:89)
    at EventEmitter.Subject.next (Subject.js?104a:55)
    at EventEmitter.emit (core.es5.js?de3d:3621)
```

And it repeats like this for a long ways

**Comment by dfederm** [comment]
It also seems to create a *new* subscriber to value changes every single time it validates. That's a massive memory leak.

**Comment by NetanelBasal** [comment]
You are right, and I'm going to fix this soon, thanks.

**Comment by NetanelBasal** [comment]
I published version 1.0.1 with the fix. Can you confirm it's working now? Thanks.

**Comment by NetanelBasal** [comment]
I am closing the issue for now.

**Comment by nilov** [comment]
Thanks for you work, but I still have this error still. I think you forget update code in dist folder.

**Comment by NetanelBasal** [comment]
Did you install version 1.0.1?

**Comment by nilov** [comment]
Yes
